version: "3"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - $BACKEND_PORT:5000
    environment:
      - ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    build:
      context: ./frontend
      # Dockerfile.dev for development, Dockerfile for production
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $FRONTEND_PORT:80
      - $FRONTEND_DEV_PORT:3000
    environment:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
