version: "3.7"

services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    build:
      context: ./frontend
      # Dockerfile.dev for development, Dockerfile for production
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
