version: "3"
services:
  nest:
    container_name: nest
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "80:80"
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
