apiVersion: v1
kind: Service
metadata:
  name: evs-be-service
spec:
  selector:
    app: evs-be-deployment
  ports:
    - name: evs-be-service
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
