name: Deploy EngVision Image
on:
  push:
    branches: ["develop", "master"]
  pull_request:
    branches: ["develop", "master"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
  VITE_SERVER_FILES_URL: ${{ secrets.VITE_SERVER_FILES_URL }}
  VITE_GA4_TRACKING_ID: ${{ secrets.VITE_GA4_TRACKING_ID }}
  VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: EngVision
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./backend
            tags: backend
          - context: ./frontend
            tags: frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ matrix.tags }}-${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_BASE_URL
            VITE_SERVER_FILES_URL
            VITE_GA4_TRACKING_ID
            VITE_SENTRY_DSN

  modify-yaml:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: EngVision

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
        name: Changing the deployment yaml
        with:
          repository: "EngVision/Engvision-Deployment"
        env:
          ACCESS_TOKEN: ${{ secrets.PAT_GH_ACTION }}
      - name: Modify the image
        run: |
          git config --global user.name 'minhtringuyennn'
          git config --global user.email 'contact@minhtringuyennn.com'
          sed -i "s+ghcr.io/engvision/project-engvision:frontend.*+ghcr.io/engvision/project-engvision:frontend-${{ github.run_number }}+g" ./k8s/evs-fe-deployment.yml
          sed -i "s+ghcr.io/engvision/project-engvision:backend.*+ghcr.io/engvision/project-engvision:backend-${{ github.run_number }}+g" ./k8s/evs-be-deployment.yml
          git add .
          git commit -m 'Github Actions - Deploy build ver ${{ github.run_number }}'
          git push origin main
        env:
          RUN_NUMBER: ${{ github.run_number }}
